# Generated by Django 3.2.9 on 2021-12-27 02:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Newsitem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dtm_created', models.DateTimeField(auto_now_add=True, verbose_name='DTM Created')),
                ('dtm_updated', models.DateTimeField(auto_now=True, verbose_name='DTM Updated')),
                ('slug', models.CharField(max_length=16, unique=True, verbose_name='Slug')),
                ('title', models.CharField(max_length=256, unique=True, verbose_name='Headline')),
                ('url', models.URLField(max_length=2048, verbose_name='URL')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('short_url', models.CharField(default=None, max_length=16, null=True, unique=True, verbose_name='Short URL')),
                ('votes', models.IntegerField(null=True)),
                ('comments', models.IntegerField(null=True)),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'News Item',
                'verbose_name_plural': 'News Items',
                'db_table': 'newsitem',
            },
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dtm_created', models.DateTimeField(auto_now_add=True, verbose_name='DTM Created')),
                ('dtm_updated', models.DateTimeField(auto_now=True, verbose_name='DTM Updated')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qux_newsfeed.newsitem')),
                ('voter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'newsitem_vote',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('identifier', models.IntegerField()),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qux_newsfeed.newsitem')),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='qux_newsfeed.comment')),
            ],
            options={
                'db_table': 'newsitem_comment',
            },
        ),
    ]
