# Generated by Django 3.2.10 on 2022-01-23 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qux_links', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='orig_url',
            field=models.URLField(blank=True, default=None, null=True, verbose_name='Original URL'),
        ),
        migrations.AlterField(
            model_name='link',
            name='type',
            field=models.CharField(choices=[('article', 'Article'), ('book', 'Book'), ('profile', 'Profile'), ('website', 'Website'), ('Music', (('song', 'Song'), ('album', 'Album'))), ('Video', (('movie', 'Movie'), ('episode', 'Episode'), ('tvshow', 'TV Show'), ('other', 'Other'))), ('File', (('file:pdf', 'PDF'), ('file:xls', 'XLS'), ('file:doc', 'DOC'), ('file:ppt', 'PPT')))], default='website', max_length=32),
        ),
    ]
